In [22]:
import numpy as np

In [23]:
X = np.array([
    [8, 4, 7],
    [2, 8, 1],
    [3, 1, 1],
    [9, 7, 4]
])

n = X.shape[0]
print("n =", n)

X_bar = X.T @ np.ones(n) / n
print("X_bar =", X_bar)

# S = (1/n * X.T @ X) - np.outer(X_bar, X_bar)
# S

S = np.cov(X, bias=True)
S

n = 4
X_bar = [5.5  5.   3.25]


array([[ 2.88888889, -4.88888889,  1.11111111,  0.44444444],
       [-4.88888889,  9.55555556, -1.11111111,  1.55555556],
       [ 1.11111111, -1.11111111,  0.88888889,  1.55555556],
       [ 0.44444444,  1.55555556,  1.55555556,  4.22222222]])

In [24]:
x1 = np.array([8, 4, 7])
x2 = np.array([2, 8, 1])
x3 = np.array([3, 1, 1])
x4 = np.array([9, 7, 4])

arrays = [x1, x2, x3, x4]

sum = 0
for array in arrays:
    sum += np.outer(array, array)
sum = sum / 4
    
S = sum - np.outer(X_bar, X_bar)
S

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

In [25]:
x1_sum = np.outer(x1, x1)
x2_sum = np.outer(x2, x2)
x3_sum = np.outer(x3, x3)
x4_sum = np.outer(x4, x4)

(x1_sum + x2_sum + x3_sum + x4_sum) / 4 - np.outer(X_bar, X_bar)

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

In [26]:
def H(x):
    p = len(x)
    H = np.eye(p) - 1/p * np.outer(np.ones(p), np.ones(p))
    return H @ x

def H2(x):
    p = len(x)
    H = np.eye(p) - 1/p * np.outer(np.ones(p), np.ones(p))
    H2 = H @ H
    return H2 @ x

In [27]:
x = np.array([2, -1, -2])

H(x)

array([ 2.33333333, -0.66666667, -1.66666667])

In [28]:
H2(x)

array([ 2.33333333, -0.66666667, -1.66666667])

In [29]:
u = 1/np.sqrt(5) * np.array([1, 2])

X1 = np.array([1, 2])
X2 = np.array([3, 4])
X3 = np.array([-1, 0])

def proj(X, u):
    return np.dot(X, u) * u

X = np.array([proj(vector, u) for vector in [X1, X2, X3]])
X

array([[ 1. ,  2. ],
       [ 2.2,  4.4],
       [-0.2, -0.4]])

In [30]:
n = X.shape[0]
print("n =", n)

H = (np.eye(n) - 1/n * np.outer(np.ones(n), np.ones(n)))

S = 1/n * X.T @ H @ X
S

n = 3


array([[0.96, 1.92],
       [1.92, 3.84]])

In [31]:
dot1 = np.dot(X1, u)
dot2 = np.dot(X2, u)
dot3 = np.dot(X3, u)

dots = np.array([dot1, dot2, dot3])
var = 1/3 * ((dot1 - dots.mean())**2 + (dot2 - dots.mean())**2 + (dot3 - dots.mean())**2)
var

4.799999999999999

In [32]:
u.T @ S @ u

4.799999999999998

In [33]:
X = np.array([
    [1, 0.5],
    [-1, -0.5]
])

X.T @ X

array([[2. , 1. ],
       [1. , 0.5]])

In [34]:
X = np.array([
    [0, 2],
    [1, -1],
    [-1, -1]
])

S = 1/2 * X.T @ X
S

array([[1., 0.],
       [0., 3.]])

In [35]:
X = np.array([
    [0, 2],
    [0, -2],
    [1, 1],
    [-1, -1]
])

n = X.shape[0]

S = 1/(n-1) * X.T @ X
S

array([[0.66666667, 0.66666667],
       [0.66666667, 3.33333333]])

In [36]:
lambda2 = 0.5092880150001402
lambda1 = 3.4907119849998596
p = 2
A = S - np.eye(p)*lambda1
B = S - np.eye(p)*lambda2

B

array([[0.15737865, 0.66666667],
       [0.66666667, 2.82404532]])

In [37]:
import scipy as sp

sp.linalg.null_space(A)

array([[0.22975292],
       [0.97324899]])

In [38]:
sp.linalg.null_space(B)

array([[-0.97324899],
       [ 0.22975292]])

In [39]:
np.real(sp.linalg.eigvals(S))

array([0.50928802, 3.49071198])

Multi-Dimensional Scaling (MDS)

In [46]:
from numpy import linalg as lg

In [42]:
X = np.array([
    [1, 1],
    [1, -1],
    [-1, 1]
])

B = X @ X.T  # Gram matrix
B

array([[ 2,  0,  0],
       [ 0,  2, -2],
       [ 0, -2,  2]])

In [44]:
np.real(sp.linalg.eigvals(B))

array([4.0000000e+00, 4.4408921e-16, 2.0000000e+00])

In [53]:
lg.eig(B)[0]  # eigenvalues

array([4.0000000e+00, 4.4408921e-16, 2.0000000e+00])

In [54]:
lg.eig(B)[1]  # eigenvectors

array([[ 0.        ,  0.        ,  1.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [47]:
1/np.sqrt(2)

0.7071067811865475