In [1]:
import numpy as np

In [3]:
np.sqrt(0.625)

0.7905694150420949

In [7]:
a = np.array(
    [0.4, 0.3]
)

b = np.array(
    [-0.15, 0.2]
)

np.linalg.norm(b)

0.25

In [12]:
theta = np.array(
    [3, 1]
)

theta_0 = -1

a = np.array(
    [-1, -1]
)

def perp_distance(theta, theta_0, x):
    return (np.dot(x, theta) + theta_0) / np.linalg.norm(theta)

In [13]:
perp_distance(theta, theta_0, a)

-1.5811388300841895

In [14]:
perp_distance(theta, theta_0, np.array([0, 0]))

-0.31622776601683794

In [17]:
def orthogonal_proj(theta, theta_0, x):
    x_proj = x - ((np.dot(x, theta) + theta_0) / np.linalg.norm(theta)**2) * theta
    return x_proj

In [18]:
orthogonal_proj(theta, theta_0, a)

array([ 0.5, -0.5])

In [19]:
import scipy.stats as st

In [20]:
P = st.norm.cdf(2, loc=1, scale=np.sqrt(2)) - st.norm.cdf(0.5, loc=1, scale=np.sqrt(2))
print(P)

0.3984131339906417


In [22]:
A = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [1, 2, 1]]
)

np.linalg.det(A)

6.0

In [23]:
np.linalg.det(A.T)

6.0

In [61]:
import numpy as np

# Example dataset
data = np.random.standard_normal(10000)

# Calculate the 0.05th quantile
quantile_005 = np.quantile(data, 0.5)
print(f"0.05th Quantile: {quantile_005}")


0.05th Quantile: 0.00431834565155151


In [63]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    return np.random.random([n, 1])

randomization(5)

array([[0.24250172],
       [0.03272057],
       [0.31495366],
       [0.09919317],
       [0.29143625]])

In [66]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h, w])
    B = np.random.random([h, w])
    
    s = A + B
    
    return A, B, s

operations(2, 3)

(array([[0.19786743, 0.94383505, 0.67774562],
        [0.91455663, 0.98146553, 0.95300384]]),
 array([[0.86567434, 0.04214444, 0.53781394],
        [0.51884658, 0.18881561, 0.25802328]]),
 array([[1.06354177, 0.98597949, 1.21555955],
        [1.43340321, 1.17028115, 1.21102712]]))

In [68]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    return np.linalg.norm(A + B)

norm(np.array([2, 2]), np.array([2, 2]))

5.656854249492381

In [74]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    return np.tanh(weights.T @ inputs)

weights = np.array([0.23963376, 0.26787957])
inputs = np.array([0.84418339, 0.20482225])

neural_network(inputs, weights)

0.2516396475770805

In [ ]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x < y:
        return x*y
    else:
        return x/y

In [ ]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    return np.vectorize(scalar_function)(x, y)

In [75]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)

print(ages)
print(heights)

[55 45 35 50 59 35 57 37 31 52]
[152 152 170 166 154 203 150 163 156 200]


In [76]:
print(ages < 50)

[False  True  True False False  True False  True  True False]


In [78]:
a = np.arange(10).reshape(1,10)
b = np.arange(12).reshape(12,1)
print(a)
print(b)

[[0 1 2 3 4 5 6 7 8 9]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [81]:
a*b

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [3]:
def double(x):
   breakpoint()
   return x * 2
val = 3
print(f"{val} * 2 is {double(val)}")


3 * 2 is 6


In [2]:
def get_sum_metrics(predictions, metrics=[]):
    for i in range(3):
        metrics.append(np.vectorize(lambda x: x + i))

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics