In [303]:
import numpy as np

def argmin_l_norm(x, Z, l):
    if l == 1:
        return np.argmin(np.sum(np.abs(x - Z), axis=1))
    elif l == 2:
        return np.argmin(np.sum((x - Z)**2, axis=1))

def kmedoids(X, k, Z=None, l=1, T=20):
    n, d = X.shape
    
    # Initialize Z
    if Z is None:
        random_indices = np.random.choice(n, size=k, replace=False)
        Z = X[random_indices, :]
    print("Z_0 =\n", Z)
    
    for t in range(T):
        print("_"*40)
        Z_old = Z
        
        # Step 1: Assign points to the nearest cluster center
        clusters = [[] for _ in range(k)]
        for x in X:
            min_index = argmin_l_norm(x, Z, l)
            clusters[min_index].append(x)
        
        print("clusters =", clusters)
        
        # Step 2: Update cluster centers
        new_Z = np.zeros_like(Z)
        for j in range(k):
            cluster_points = np.vstack(clusters[j])
            # print("cluster_points.shape =", cluster_points.shape)
            # print("cluster_points[:, np.newaxis] =\n", cluster_points[:, np.newaxis])
            # Find the medoid
            if l == 1: 
                medoid_index = np.argmin(np.sum(np.abs(cluster_points[:, np.newaxis] - cluster_points[np.newaxis, :]), axis=2).sum(axis=1))
            elif l == 2:
                medoid_index = np.argmin(np.sum((cluster_points[:, np.newaxis] - cluster_points[np.newaxis, :])**2, axis=2).sum(axis=1))
            new_Z[j] = cluster_points[medoid_index]
        
        print("  new_Z =", new_Z)
        
        # Check for convergence (optional)
        if np.all(new_Z == Z):
            break
        
        Z = new_Z
    
    return Z, clusters

# Define the dataset
X = np.array([
    [0, -6],
    [4, 4],
    [0, 0],
    [-5, 2]
])

# Initial cluster centers
initial_Z = np.array([
    [-5, 2],
    [0, -6]
])

# Run k-medoids
final_Z, final_clusters = kmedoids(X, k=2, Z=initial_Z, l=2)

print("\nFinal cluster centers:")
print(final_Z)
print("\nFinal clusters:")
for i, cluster in enumerate(final_clusters):
    print(f"Cluster {i}: {cluster}")


Z_0 =
 [[-5  2]
 [ 0 -6]]
________________________________________
clusters = [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
  new_Z = [[ 0  0]
 [ 0 -6]]
________________________________________
clusters = [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
  new_Z = [[ 0  0]
 [ 0 -6]]

Final cluster centers:
[[ 0  0]
 [ 0 -6]]

Final clusters:
Cluster 0: [array([4, 4]), array([0, 0]), array([-5,  2])]
Cluster 1: [array([ 0, -6])]


In [304]:
X = np.array([
    [0, -6],
    [4, 4],
    [0, 0],
    [-5, 2]
])

Z = np.array([
    [-5, 2],
    [0, 6]
])

kmedoids(X, 2, Z=Z, l=1, T=5)

Z_0 =
 [[-5  2]
 [ 0  6]]
________________________________________
clusters = [[array([-5,  2])], [array([ 0, -6]), array([4, 4]), array([0, 0])]]
  new_Z = [[-5  2]
 [ 0  0]]
________________________________________
clusters = [[array([-5,  2])], [array([ 0, -6]), array([4, 4]), array([0, 0])]]
  new_Z = [[-5  2]
 [ 0  0]]


(array([[-5,  2],
        [ 0,  0]]),
 [[array([-5,  2])], [array([ 0, -6]), array([4, 4]), array([0, 0])]])

In [305]:
import numpy as np

# Function to calculate the index of the closest centroid based on L1 norm
def argmin_l_norm(x, Z, l):
    if l == 1:
        return np.argmin(np.sum(np.abs(x - Z), axis=1))
    elif l == 2:
        return np.argmin(np.sum((x - Z)**2, axis=1))

# K-means with L1 norm
def kmeans_l1(X, k, Z=None, T=20):
    n, d = X.shape
    
    # Initialize Z if not provided
    if Z is None:
        random_indices = np.random.choice(n, size=k, replace=False)
        Z = X[random_indices, :]
    print("Initial Z (centroids):\n", Z)
    
    for t in range(T):
        print("_" * 40)
        
        # Step 1: Assign points to the nearest cluster center
        clusters = [[] for _ in range(k)]
        for x in X:
            min_index = argmin_l_norm(x, Z, l=1)
            clusters[min_index].append(x)
        
        print("clusters =", clusters)
        
        # Step 2: Update cluster centers
        new_Z = np.zeros_like(Z)
        for j in range(k):
            cluster_points = np.vstack(clusters[j])  # data points are row vectors
            print(f"cluster_points {j} =", cluster_points)
            # Find the median
            new_Z[j] = np.median(cluster_points, axis=0)
        
        print("  new_Z =", new_Z)
        
        # Check for convergence
        if np.allclose(new_Z, Z):  # Using np.allclose for better numerical stability
            break
        
        Z = new_Z
    
    return Z, clusters

# Define the dataset
X = np.array([
    [0, -6],
    [4, 4],
    [0, 0],
    [-5, 2]
])

# Initial cluster centers
initial_Z = np.array([
    [-5, 2],
    [0, -6]
])

# Run k-means with L1 norm
final_Z, final_clusters = kmeans_l1(X, k=2, Z=initial_Z, T=20)

print("\nFinal cluster centers:")
print(final_Z)
print("\nFinal clusters:")
for i, cluster in enumerate(final_clusters):
    print(f"Cluster {i}: {cluster}")


Initial Z (centroids):
 [[-5  2]
 [ 0 -6]]
________________________________________
clusters = [[array([4, 4]), array([-5,  2])], [array([ 0, -6]), array([0, 0])]]
cluster_points 0 = [[ 4  4]
 [-5  2]]
cluster_points 1 = [[ 0 -6]
 [ 0  0]]
  new_Z = [[ 0  3]
 [ 0 -3]]
________________________________________
clusters = [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
cluster_points 0 = [[ 4  4]
 [ 0  0]
 [-5  2]]
cluster_points 1 = [[ 0 -6]]
  new_Z = [[ 0  2]
 [ 0 -6]]
________________________________________
clusters = [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
cluster_points 0 = [[ 4  4]
 [ 0  0]
 [-5  2]]
cluster_points 1 = [[ 0 -6]]
  new_Z = [[ 0  2]
 [ 0 -6]]

Final cluster centers:
[[ 0  2]
 [ 0 -6]]

Final clusters:
Cluster 0: [array([4, 4]), array([0, 0]), array([-5,  2])]
Cluster 1: [array([ 0, -6])]


In [306]:
import numpy as np

# Function to calculate the index of the closest centroid based on L1 norm
def argmin_l_norm(x, Z):
    return np.argmin(np.sum(np.abs(x - Z), axis=1))

# K-means with L1 norm
def kmeans_l1(X, k, Z=None, T=20):
    n, d = X.shape
    
    # Initialize Z if not provided
    if Z is None:
        random_indices = np.random.choice(n, size=k, replace=False)
        Z = X[random_indices, :]
    print("Initial Z (centroids):\n", Z)
    
    for t in range(T):
        print("_" * 40)
        
        # Step 1: Assign points to the nearest cluster center
        clusters = [[] for _ in range(k)]
        for x in X:
            min_index = argmin_l_norm(x, Z)
            clusters[min_index].append(x)
        
        print("Clusters:", clusters)
        
        # Step 2: Update cluster centers
        new_Z = np.zeros_like(Z)
        for j in range(k):
            cluster_points = np.vstack(clusters[j])  # data points are row vectors
            print(f"cluster_points {j} =", cluster_points)
            # Find the median
            new_Z[j] = np.median(cluster_points, axis=0)
        
        print("New Z (centroids):", new_Z)
        
        # Check for convergence
        if np.allclose(new_Z, Z):  # Using np.allclose for better numerical stability
            break
        
        Z = new_Z
    
    return Z, clusters

# Define the dataset
X = np.array([
    [0, -6],
    [4, 4],
    [0, 0],
    [-5, 2]
])

# Initial cluster centers
initial_Z = np.array([
    [-5, 2],
    [0, -6]
])

# Run k-means with L1 norm
final_Z, final_clusters = kmeans_l1(X, k=2, Z=initial_Z, T=20)

print("\nFinal cluster centers:")
print(final_Z)
print("\nFinal clusters:")
for i, cluster in enumerate(final_clusters):
    print(f"Cluster {i}: {cluster}")


Initial Z (centroids):
 [[-5  2]
 [ 0 -6]]
________________________________________
Clusters: [[array([4, 4]), array([-5,  2])], [array([ 0, -6]), array([0, 0])]]
cluster_points 0 = [[ 4  4]
 [-5  2]]
cluster_points 1 = [[ 0 -6]
 [ 0  0]]
New Z (centroids): [[ 0  3]
 [ 0 -3]]
________________________________________
Clusters: [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
cluster_points 0 = [[ 4  4]
 [ 0  0]
 [-5  2]]
cluster_points 1 = [[ 0 -6]]
New Z (centroids): [[ 0  2]
 [ 0 -6]]
________________________________________
Clusters: [[array([4, 4]), array([0, 0]), array([-5,  2])], [array([ 0, -6])]]
cluster_points 0 = [[ 4  4]
 [ 0  0]
 [-5  2]]
cluster_points 1 = [[ 0 -6]]
New Z (centroids): [[ 0  2]
 [ 0 -6]]

Final cluster centers:
[[ 0  2]
 [ 0 -6]]

Final clusters:
Cluster 0: [array([4, 4]), array([0, 0]), array([-5,  2])]
Cluster 1: [array([ 0, -6])]
