In [3]:
import numpy as np

In [4]:
X = np.array([
    [3, 2],
    [1, 1],
    [4, 2]
])
y = np.array([1, -1, -1])
X = np.hstack((X, np.ones((X.shape[0], 1))))
print(X)
theta = np.array([1, 1, -4])
margins = y * (X@theta / np.linalg.norm(theta[:-1]))
margins


[[3. 2. 1.]
 [1. 1. 1.]
 [4. 2. 1.]]


array([ 0.70710678,  1.41421356, -1.41421356])

In [5]:
data = np.array([[1, 1, 3, 3],[3, 1, 4, 2]])
labels = np.array([[-1, -1, 1, 1]])
th = np.array([[0, 1]]).T
th0 = -3
theta = np.vstack((th, np.array([[-3]])))
print("theta =\n", theta)

theta =
 [[ 0]
 [ 1]
 [-3]]


In [11]:
def f(x):  # Objective function
    return (2*x + 3)**2

def f_1(x):  # first derivative of f(x)
    return 8*x + 12

np.round([1 - 8*eta for eta in [0.1, 0.11, 0.12, 0.13, 0.14, 0.15]], 6)

array([ 0.2 ,  0.12,  0.04, -0.04, -0.12, -0.2 ])